name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          npm install

      - name: Install Danger
        run: npm install -g danger

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
        run: danger pr https://api.github.com/repos/su-brat/institute-app/pulls?state=open
